package com.zmsoft.TestTool.constants;

/**
 * Created by gly on 2017/9/22.
 */

public enum  SpeechConstants {
    RMB,SHITANG_DINGDAN,WAI_MAI,NEW_TO_RESOLVE,NEW_PAY_SUCCESS,IS_RECEIVE,HELLO_USE_SYSTEM,SELF_ORDER,
    ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO, CHECK_FAIL, CHECK_SUCCESS, ELEME_DINGDAN, ZIYING_DINGDAN, ZITI_DINGDAN, MEITUAN_DINGDAN, BAIDU_DINGDAN, DING_DONG, POINT
}
